// Command gen-site-docs regenerates the site's command reference from the CLI
// definition, so the documented flags can't drift from the flags kx accepts.
//
//	go run ./tools/gen-site-docs
//
// Writes site/content/docs/reference/commands/: an overview page grouped the
// way the root help screen groups commands, and one page per command carrying
// the same structured help `kx <command> --help` renders.
//
// Same contract as gen-command-table and gen-site-theme: run by a pre-commit
// hook, exits non-zero when it rewrote anything so the change is surfaced for
// staging rather than committed stale. .github/workflows/pages.yml runs it and
// diffs, so a flag added without regenerating fails there too.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jzills/kx/internal/cli"
	"github.com/jzills/kx/internal/render"
	"github.com/jzills/kx/tools/internal/cmddoc"
	"github.com/spf13/cobra"
)

const outputDir = "site/content/docs/reference/commands"

// generatedBy is a YAML comment rather than an HTML one: it is for whoever
// opens the file to edit it, and a reader of the published page has no use for
// it. Hugo's front matter parser drops comments, so it never reaches the HTML.
const generatedBy = "# Generated by tools/gen-site-docs from internal/cli. Do not edit."

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	pages, err := Pages()
	if err != nil {
		return err
	}

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}

	var changed []string
	for name, body := range pages {
		path := filepath.Join(outputDir, name)
		current, err := os.ReadFile(path)
		if err == nil && string(current) == body {
			continue
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return err
		}
		changed = append(changed, name)
	}

	// A command that was renamed or removed leaves its page behind, still
	// listed by search and still linked by anyone who bookmarked it. Nothing
	// else writes to this directory, so anything not generated this run is
	// stale by definition.
	stale, err := filepath.Glob(filepath.Join(outputDir, "*.md"))
	if err != nil {
		return err
	}
	for _, path := range stale {
		if _, generated := pages[filepath.Base(path)]; generated {
			continue
		}
		if err := os.Remove(path); err != nil {
			return err
		}
		changed = append(changed, "removed "+filepath.Base(path))
	}

	if len(changed) == 0 {
		fmt.Printf("%s is up to date.\n", outputDir)
		return nil
	}
	sort.Strings(changed)
	// Non-zero so pre-commit surfaces the rewrite for staging.
	return fmt.Errorf("updated %s:\n  %s", outputDir, strings.Join(changed, "\n  "))
}

// Pages renders the whole reference, keyed by file name. Separated from run so
// a test can assert on the content without touching the filesystem.
func Pages() (map[string]string, error) {
	byName := cmddoc.Commands()

	pages := map[string]string{}
	weight := 0
	for _, name := range cli.CommandOrder() {
		cmd, ok := byName[name]
		if !ok {
			return nil, fmt.Errorf("command %q is listed in the help sections but not registered", name)
		}
		weight++
		pages[name+".md"] = commandPage(cmd, weight)
	}

	index, err := overview(byName)
	if err != nil {
		return nil, err
	}
	pages["_index.md"] = index
	return pages, nil
}

// overview is the section index: every command, in the groups the root help
// screen uses, each row linking to its page.
func overview(byName map[string]*cobra.Command) (string, error) {
	var out strings.Builder
	out.WriteString(frontMatter(
		"Commands",
		"Commands",
		"Every kx command, its arguments and its flags.",
		1,
	))
	out.WriteString("\nEvery command below takes indexes from the listing " +
		"`kx get` last produced. Run `kx <command> --help` for the same " +
		"reference in the terminal.\n")

	for _, section := range cli.HelpSections() {
		out.WriteString("\n## " + section.Title + "\n\n")
		out.WriteString("| Command | Description |\n|---|---|\n")
		for _, name := range section.Commands {
			cmd, ok := byName[name]
			if !ok {
				return "", fmt.Errorf(
					"command %q is listed in the help sections but not registered", name)
			}
			out.WriteString(fmt.Sprintf("| [`%s`](%s/) | %s |\n",
				cmddoc.Signature(cmd), name, cell(oneLine(cmd.Short))))
		}
	}
	return out.String(), nil
}

func commandPage(cmd *cobra.Command, weight int) string {
	help := cli.HelpFor(cmd)

	var out strings.Builder
	out.WriteString(frontMatter(help.Path, cmd.Name(), oneLine(cmd.Short), weight))

	if help.Doc != "" {
		out.WriteString("\n" + help.Doc + "\n")
	}

	out.WriteString("\n## Usage\n\n```text\n" + help.Usage + "\n```\n")

	if len(help.Aliases) > 0 {
		spellings := make([]string, 0, len(help.Aliases))
		for _, alias := range help.Aliases {
			spellings = append(spellings, "`kx "+alias+"`")
		}
		out.WriteString("\n## Aliases\n\n" + strings.Join(spellings, ", ") + "\n")
	}

	writeTable(&out, "Subcommands", "Command", help.Commands, func(item render.HelpItem) string {
		return "`" + help.Path + " " + item.Name + "`"
	})
	writeTable(&out, "Arguments", "Argument", help.Args, nil)
	writeTable(&out, "Options", "Option", help.Options, nil)
	writeTable(&out, "Global options", "Option", help.Global, nil)

	if len(help.Examples) > 0 {
		out.WriteString("\n## Examples\n\n```bash\n" +
			strings.Join(help.Examples, "\n") + "\n```\n")
	}
	return out.String()
}

// writeTable renders one section of the page, or nothing at all when the
// command has no items of that kind — an empty "Arguments" heading says less
// than no heading.
//
// spell renders the name column; nil means backticks around the name as given.
func writeTable(
	out *strings.Builder, title, column string,
	items []render.HelpItem, spell func(render.HelpItem) string,
) {
	if len(items) == 0 {
		return
	}
	if spell == nil {
		spell = func(item render.HelpItem) string { return "`" + item.Name + "`" }
	}
	out.WriteString("\n## " + title + "\n\n")
	out.WriteString("| " + column + " | Description |\n|---|---|\n")
	for _, item := range items {
		out.WriteString("| " + spell(item) + " | " + cell(item.Doc) + " |\n")
	}
}

func frontMatter(title, linkTitle, description string, weight int) string {
	return strings.Join([]string{
		"---",
		generatedBy,
		"title: " + quote(title),
		"linkTitle: " + quote(linkTitle),
		"description: " + quote(description),
		fmt.Sprintf("weight: %d", weight),
		"---",
		"",
	}, "\n")
}

// quote writes a YAML double-quoted scalar. Command descriptions carry colons
// ("shorthand: kx <kind>"), which end a plain scalar and would make the file
// unparseable.
func quote(value string) string {
	escaped := strings.ReplaceAll(value, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return `"` + escaped + `"`
}

// cell escapes prose for a markdown table.
//
// Pipes would end the cell. Angle brackets are the subtler one: goldmark runs
// with unsafe HTML on for the landing page's hand-written markup, so `kx
// <kind>` in a description is parsed as a tag and silently disappears from the
// rendered page — which is what `kx get`'s own summary says.
func cell(text string) string {
	replacer := strings.NewReplacer("|", `\|`, "<", "&lt;", ">", "&gt;")
	return replacer.Replace(oneLine(text))
}

// oneLine collapses the wrapped Go string literals the help screens are written
// as, so a description spanning source lines is still one table cell.
func oneLine(text string) string {
	return strings.Join(strings.Fields(text), " ")
}
