package index

import (
	"encoding/json"
	"os"
	"testing"
)

// Byte-for-byte parity with the Python implementation.
//
// testdata/python_golden.json is generated by running the real kx.index
// IndexService over these fixtures (see the regeneration command below), so
// this fails if the Go port drifts on column widths, padding, dedupe order, or
// the no-match fallback — differences the hand-written tests would not catch
// because both sides would be written to the same assumption.
//
// Regenerate after an intentional change to either implementation:
//
//	python scripts/gen_index_golden.py > internal/index/testdata/python_golden.json
//
// This file, the fixtures and the generator are deleted along with the Python
// implementation at cutover.
type goldenCase struct {
	Input      string   `json:"input"`
	Add        string   `json:"add"`
	Names      []string `json:"names"`
	FilterA    string   `json:"filter_a"`
	FilterNone string   `json:"filter_none"`
}

func TestParityWithPythonImplementation(t *testing.T) {
	data, err := os.ReadFile("testdata/python_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var cases map[string]goldenCase
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	if len(cases) == 0 {
		t.Fatal("golden file is empty")
	}

	service := Service{}
	for name, want := range cases {
		t.Run(name, func(t *testing.T) {
			gotAdd, gotNames := service.Add(want.Input)
			if gotAdd != want.Add {
				t.Errorf("Add mismatch\n go: %q\n py: %q", gotAdd, want.Add)
			}
			if len(gotNames) != len(want.Names) {
				t.Fatalf("names = %v, want %v", gotNames, want.Names)
			}
			for i := range want.Names {
				if gotNames[i] != want.Names[i] {
					t.Errorf("names[%d] = %q, want %q", i, gotNames[i], want.Names[i])
				}
			}
			if got := service.Filter(want.Input, "a"); got != want.FilterA {
				t.Errorf("Filter(_, \"a\") mismatch\n go: %q\n py: %q", got, want.FilterA)
			}
			if got := service.Filter(want.Input, "zzz-no-match"); got != want.FilterNone {
				t.Errorf("Filter(_, no-match) mismatch\n go: %q\n py: %q", got, want.FilterNone)
			}
		})
	}
}
