// Command gen-demo-tapes writes one VHS tape per palette, from demo/demo.tape.
//
//	go run ./tools/gen-demo-tapes
//
// Two things have to change per palette, and they are different things. kx's
// own theme decides how kx colours its output; VHS's Set Theme decides what the
// terminal around it looks like. Recording a light kx palette on a black
// terminal would look like neither, so the terminal's background and foreground
// are taken from the same palette.
//
// The recordings land under site/static/, and the tapes beside them in site/
// rather than in it — a tape is source, and anything under static/ is published.
// Both sit under site/ because it is a nested Go module, which keeps 15 MB of
// recordings out of the kx module zip that `go install` downloads.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/jzills/kx/internal/theme"
)

const (
	sourceTape = "demo/demo.tape"
	outputDir  = "site/static/demo"
	tapeDir    = "site/tapes"
)

func main() {
	source, err := os.ReadFile(sourceTape)
	if err != nil {
		fail(err)
	}
	if err := os.MkdirAll(tapeDir, 0o755); err != nil {
		fail(err)
	}

	for _, name := range palettes() {
		tape, err := renderTape(string(source), name)
		if err != nil {
			fail(fmt.Errorf("%s: %w", name, err))
		}
		path := filepath.Join(tapeDir, "demo-"+name+".tape")
		if err := os.WriteFile(path, []byte(tape), 0o644); err != nil {
			fail(err)
		}
		fmt.Println("wrote", path)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-demo-tapes:", err)
	os.Exit(2)
}

func palettes() []string {
	var kept []string
	for _, name := range theme.Names() {
		if name != "plain" {
			kept = append(kept, name)
		}
	}
	return kept
}

var (
	outputDirective = regexp.MustCompile(`(?m)^Output .*$`)
	themeDirective  = regexp.MustCompile(`(?m)^Set Theme .*$`)
)

func renderTape(source, palette string) (string, error) {
	terminal, err := terminalTheme(palette)
	if err != nil {
		return "", err
	}

	tape := outputDirective.ReplaceAllString(source, "")
	tape = themeDirective.ReplaceAllString(tape, "Set Theme "+terminal)

	// Every Set has to precede the first Env, or VHS ignores it — it warns
	// "has been ignored, move the directive to the top of the file" and records
	// with its own defaults. Emitting Env first cost a whole batch of
	// recordings their palette, their size and their font before the warning
	// was read, so the settings are lifted out and re-emitted in order rather
	// than left wherever the source tape happened to put them.
	settings, rest := splitSettings(tape)

	var out strings.Builder
	fmt.Fprintf(&out, "# Generated by tools/gen-demo-tapes for the %s palette. Do not edit.\n"+
		"# Regenerate with: go run ./tools/gen-demo-tapes\n\n", palette)
	for _, line := range settings {
		out.WriteString(line + "\n")
	}
	// KX_THEME renders kx's own output in this palette without touching
	// ~/.kx/config.toml, unlike demo/render.sh which switches the configured
	// theme and has to put it back.
	fmt.Fprintf(&out, "\nEnv KX_THEME %q\n", palette)
	fmt.Fprintf(&out, "Output %s/demo-%s.gif\n", outputDir, palette)
	out.WriteString(strings.TrimLeft(rest, "\n"))
	return out.String(), nil
}

// splitSettings separates the Set directives from everything else, preserving
// the order of each.
func splitSettings(tape string) (settings []string, rest string) {
	var others []string
	for _, line := range strings.Split(tape, "\n") {
		switch {
		case strings.HasPrefix(strings.TrimSpace(line), "Set "):
			settings = append(settings, strings.TrimSpace(line))
		default:
			others = append(others, line)
		}
	}
	return settings, strings.Join(others, "\n")
}

// terminalTheme renders the VHS terminal palette as the JSON its Set Theme
// directive takes.
//
// The ANSI slots are filled from the semantic colours kx actually uses, so a
// command that prints red prints the palette's red, and the terminal's own
// chrome agrees with it.
func terminalTheme(palette string) (string, error) {
	styles, err := theme.WebStyles(palette)
	if err != nil {
		return "", err
	}

	background := styles[theme.Background]
	body := styles[theme.Body]
	accent := styles[theme.Accent]
	bad := styles[theme.Error]
	warn := styles[theme.Warn]
	muted := styles[theme.Muted]

	// Ordered so the generated tapes are byte-stable; encoding/json sorts map
	// keys, which is what makes rerunning this a no-op when nothing changed.
	terminal := map[string]string{
		"background": background,
		"foreground": body,
		"cursor":     accent,
		"black":      background,
		"red":        bad,
		"green":      accent,
		"yellow":     warn,
		"blue":       muted,
		"magenta":    accent,
		"cyan":       muted,
		"white":      body,
		// kx's muted style resolves to a bright black on many palettes, so the
		// bright slots have to carry real colours rather than be left to the
		// terminal's defaults.
		"brightBlack":   muted,
		"brightRed":     bad,
		"brightGreen":   accent,
		"brightYellow":  warn,
		"brightBlue":    muted,
		"brightMagenta": accent,
		"brightCyan":    muted,
		"brightWhite":   body,
	}

	encoded, err := json.Marshal(terminal)
	if err != nil {
		return "", err
	}
	return string(encoded), nil
}
