// Command gen-marks draws the kx mark as vector shapes.
//
//	go run ./tools/gen-marks
//
// The mark is ASCII art, read from internal/mark — the same lines, and the
// same variable, kx prints at the top of --help. Every SVG of it used to be
// that art as <text> in a monospace font, which only lines up when the reader
// has the font. Chromium without Courier New, and GitHub's own renderer, both
// showed it as a jumble of offset blocks.
//
// Emitting rectangles removes the font from the picture: the same shapes
// render on every machine, at every size, and stay crisp when scaled. Every
// output below shares one grid of rects; only the wrapping markup differs, so
// the marks can never drift out of shape with each other.
//
// Run it after editing mark.Lines — the SVGs are committed, so a change to
// the art reaches the README, the site and the report only from here. The
// pre-commit hook runs it for exactly that reason.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/jzills/kx/internal/mark"
)

// The README banner is embedded via <img width="800">, wide of the mark's own
// 4:3 shape, so its canvas keeps the original text version's proportions —
// the mark centred with letterbox padding — rather than cropping to it.
const (
	bannerWidth  = 800.0
	bannerHeight = 250.0
)

// outputs is every place the mark is drawn as a vector. Each gets the same
// grid of rects, wrapped in the markup its own page expects.
var outputs = []struct {
	path string
	// open renders everything before the rects, close everything after, for a
	// mark w wide and h tall.
	open, close func(w, h float64) string
}{
	{
		// The site colours the mark from the active palette by inheriting
		// fill from the SVG's own fill="currentColor", set through CSS.
		path: "site/assets/kx-mark.svg",
		open: func(w, h float64) string {
			return fmt.Sprintf(
				"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 %g %g\"\n"+
					"     fill=\"currentColor\" shape-rendering=\"crispEdges\"\n"+
					"     role=\"img\" aria-label=\"kx\">\n", w, h)
		},
		close: func(w, h float64) string { return "</svg>\n" },
	},
	{
		// The --html report masthead colours the mark via .wordmark's own
		// fill: var(--accent) in internal/web/style.css, so the rects here
		// carry no fill of their own and just inherit it.
		path: "internal/web/wordmark.svg",
		open: func(w, h float64) string {
			return fmt.Sprintf(
				"<svg class=\"wordmark\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 %g %g\"\n"+
					"     shape-rendering=\"crispEdges\" role=\"img\" aria-label=\"kx\">\n", w, h)
		},
		close: func(w, h float64) string { return "</svg>\n" },
	},
	{
		// GitHub renders READMEs standalone, with no page palette to inherit
		// from, so this one carries its own fixed fill rather than
		// currentColor. The mark is centred in a canvas the size the <text>
		// version used, so the banner keeps its wide, padded proportions
		// instead of shrinking to the mark's own tighter 4:3 shape.
		path: "assets/banner.svg",
		open: func(w, h float64) string {
			return fmt.Sprintf(
				"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"%g\" height=\"%g\" viewBox=\"0 0 %g %g\"\n"+
					"     shape-rendering=\"crispEdges\" role=\"img\" aria-label=\"kx — kubectl, indexed.\">\n"+
					"  <g fill=\"#3fb950\" transform=\"translate(%g, %g)\">\n",
				bannerWidth, bannerHeight, bannerWidth, bannerHeight,
				(bannerWidth-w)/2, (bannerHeight-h)/2)
		},
		close: func(w, h float64) string { return "  </g>\n</svg>\n" },
	},
}

func main() {
	shapes, w, h := mark.Shapes()

	var drawn strings.Builder
	for _, shape := range shapes {
		fmt.Fprintf(&drawn, "  <rect x=\"%g\" y=\"%g\" width=\"%g\" height=\"%g\"/>\n",
			shape.X, shape.Y, shape.Width, shape.Height)
	}

	for _, output := range outputs {
		var out strings.Builder
		out.WriteString(
			"<!-- Generated by tools/gen-marks. Do not edit.\n" +
				"     The kx mark as rectangles rather than text: drawn as <text> it only\n" +
				"     lines up where the reader has a monospace font carrying the box-drawing\n" +
				"     glyphs, and falls apart into offset blocks where they don't. -->\n")
		out.WriteString(output.open(w, h))
		out.WriteString(drawn.String())
		out.WriteString(output.close(w, h))

		if err := write(output.path, []byte(out.String())); err != nil {
			fmt.Fprintln(os.Stderr, "gen-marks:", err)
			os.Exit(2)
		}
	}

	if err := writeFavicons(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-marks:", err)
		os.Exit(2)
	}
}
