// Command gen-site-terminal captures real kx output, in every palette, as HTML
// for the site.
//
//	go run ./tools/gen-site-terminal
//
// Not a mock of a terminal. kx is run for real, under a pty so it emits the
// styling it would emit to a terminal, and the ANSI is converted to spans. The
// colours in that stream are the palette's own literal values — truecolor SGR
// carries #rrggbb exactly — so the conversion loses nothing.
//
// One capture per palette rather than one capture mapped back onto CSS
// variables: within a palette several semantic styles share a colour
// (github-dark draws accent, success and status.ok all in #3fb950), so a
// colour cannot be mapped back to the style that produced it. Capturing per
// palette sidesteps the ambiguity entirely and still costs about 2 KB each.
//
// Requires a seeded demo cluster — see demo/seed.sh — so this is run by hand
// like demo/render.sh, and its output is committed.
package main

import (
	"fmt"
	"html"
	"os"
	"os/exec"
	"regexp"
	"strconv"
	"strings"

	"github.com/jzills/kx/internal/theme"
)

const outputPath = "site/layouts/_partials/kx-terminal.html"

// command is what the sample shows. Kept short: the listing is the point, and
// a taller block pushes the rest of the page below the fold.
var command = []string{"get", "pods", "-n", "diagnostics"}

// maxRows caps the captured listing so a seeded cluster that grew does not
// silently lengthen the page.
const maxRows = 9

func main() {
	binary, err := buildKx()
	if err != nil {
		fail(err)
	}
	defer os.Remove(binary)

	var out strings.Builder
	out.WriteString("{{- /*\n" +
		"  Generated by tools/gen-site-terminal. Do not edit.\n\n" +
		"  Real `kx " + strings.Join(command, " ") + "` output, captured under a pty once per\n" +
		"  palette and converted from ANSI. Only the block matching the active\n" +
		"  palette is shown; the rest are display:none, which is what lets the\n" +
		"  sample change theme with the page.\n" +
		"*/ -}}\n")

	for _, name := range palettes() {
		captured, err := capture(binary, name)
		if err != nil {
			fail(fmt.Errorf("%s: %w", name, err))
		}
		fmt.Fprintf(&out, "<div class=\"kx-terminal\" data-kx-terminal=%q>\n<pre>%s</pre>\n</div>\n",
			name, captured)
	}

	if err := os.WriteFile(outputPath, []byte(out.String()), 0o644); err != nil {
		fail(err)
	}
	fmt.Println("updated", outputPath)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-site-terminal:", err)
	os.Exit(2)
}

func palettes() []string {
	var kept []string
	for _, name := range theme.Names() {
		// "plain" emits no styling at all, so its capture would be a grey
		// block; the site does not offer it either. See tools/gen-site-theme.
		if name != "plain" {
			kept = append(kept, name)
		}
	}
	return kept
}

// buildKx compiles the working tree's kx, so the sample shows what the code
// being committed actually prints.
func buildKx() (string, error) {
	binary, err := os.CreateTemp("", "kx-sample-*")
	if err != nil {
		return "", err
	}
	binary.Close()
	build := exec.Command("go", "build", "-o", binary.Name(), "./cmd/kx")
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		return "", fmt.Errorf("building kx: %w", err)
	}
	return binary.Name(), nil
}

// capture runs kx under a pty in the named palette and returns its output as
// HTML.
//
// script(1) supplies the pty: kx styles output only when stdout is a terminal,
// so a plain pipe would capture the unstyled form. COLORTERM asks termenv for
// truecolor, which is what makes the emitted colours the palette's exact hex
// rather than the nearest of 256.
func capture(binary, palette string) (string, error) {
	run := exec.Command("script", "-qec",
		strings.Join(append([]string{binary}, command...), " "), "/dev/null")
	run.Env = append(os.Environ(),
		"KX_THEME="+palette,
		"COLORTERM=truecolor",
		"TERM=xterm-256color",
		// script(1) inherits the caller's width; pinning it keeps every
		// palette's capture the same shape and stops a wide terminal padding
		// the sample out to 200 columns.
		"COLUMNS=98",
	)
	output, err := run.Output()
	if err != nil {
		return "", err
	}
	return toHTML(string(output)), nil
}

// sgr matches one ANSI select-graphic-rendition sequence.
var sgr = regexp.MustCompile(`\x1b\[([0-9;]*)m`)

// toHTML converts a captured ANSI stream to spans.
func toHTML(raw string) string {
	var out strings.Builder
	rows := 0

	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimRight(strings.ReplaceAll(line, "\r", ""), " ")
		if line == "" {
			continue
		}
		if rows >= maxRows {
			break
		}
		rows++
		out.WriteString(convertLine(line))
		out.WriteString("\n")
	}
	return strings.TrimRight(out.String(), "\n")
}

// convertLine turns one line's escape sequences into spans, closing any span
// still open at the end so the markup stays balanced.
func convertLine(line string) string {
	var out strings.Builder
	open := false
	last := 0

	for _, match := range sgr.FindAllStringSubmatchIndex(line, -1) {
		out.WriteString(html.EscapeString(line[last:match[0]]))
		last = match[1]

		if open {
			out.WriteString("</span>")
			open = false
		}
		if style := styleFor(line[match[2]:match[3]]); style != "" {
			fmt.Fprintf(&out, "<span style=%q>", style)
			open = true
		}
	}
	out.WriteString(html.EscapeString(line[last:]))
	if open {
		out.WriteString("</span>")
	}
	return out.String()
}

// styleFor renders one SGR parameter list as inline CSS. Only the attributes
// kx emits are handled — bold and truecolor foregrounds — and a reset returns
// the empty string, which closes the open span without opening another.
func styleFor(parameters string) string {
	if parameters == "" || parameters == "0" {
		return ""
	}
	fields := strings.Split(parameters, ";")

	var declarations []string
	for i := 0; i < len(fields); i++ {
		switch fields[i] {
		case "0":
			declarations = nil
		case "1":
			declarations = append(declarations, "font-weight:700")
		case "38":
			// 38;2;R;G;B — a truecolor foreground.
			if i+4 < len(fields) && fields[i+1] == "2" {
				red, green, blue := fields[i+2], fields[i+3], fields[i+4]
				if isByte(red) && isByte(green) && isByte(blue) {
					declarations = append(declarations,
						fmt.Sprintf("color:rgb(%s,%s,%s)", red, green, blue))
				}
				i += 4
			}
		}
	}
	return strings.Join(declarations, ";")
}

func isByte(value string) bool {
	number, err := strconv.Atoi(value)
	return err == nil && number >= 0 && number <= 255
}
