// Command gen-site-theme writes the kx palettes out as CSS for the Hugo site,
// so the website, the terminal and the --html reports are colored from one
// registry rather than three copies of the same hex values.
//
//	go run ./tools/gen-site-theme
//
// Run by the gen-site-theme pre-commit hook. Exits non-zero when it rewrote the
// stylesheet, so the hook surfaces the change for staging rather than
// committing a stale one — the same contract gen-command-table has.
package main

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/jzills/kx/internal/theme"
)

const (
	outputPath = "site/assets/css/kx-themes.css"
	// dataPath feeds the site's theme picker. Emitted here rather than listed
	// in a template so the picker cannot offer a palette the stylesheet has no
	// block for, or miss one it does.
	dataPath = "site/data/kx_themes.json"
)

// defaultDark and defaultLight are the palettes Hextra's own light/dark toggle
// maps onto. Every other palette is reachable only by explicit choice.
const (
	defaultDark  = "github-dark"
	defaultLight = "light"
)

// skipped palettes make no sense as a website theme.
//
// "plain" means "no terminal styling"; it has no web identity of its own and
// WebStyles returns exactly what "mono" returns, so listing it would put a
// duplicate in the site's theme picker.
var skipped = map[string]bool{"plain": true}

func main() {
	css, err := render()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-site-theme:", err)
		os.Exit(2)
	}
	data, err := renderData()
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-site-theme:", err)
		os.Exit(2)
	}

	changed := false
	for _, file := range []struct{ path, contents string }{
		{outputPath, css},
		{dataPath, data},
	} {
		existing, readErr := os.ReadFile(file.path)
		if readErr == nil && string(existing) == file.contents {
			continue
		}
		if err := os.WriteFile(file.path, []byte(file.contents), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "gen-site-theme:", err)
			os.Exit(2)
		}
		fmt.Println("updated", file.path)
		changed = true
	}
	if changed {
		os.Exit(1)
	}
}

// renderData writes the palette list the picker iterates: the name it sets on
// the document, the two colors its swatch shows, and whether the palette reads
// as light or dark overall.
//
// Mode exists because Hextra has its own light/dark switch, wired to a "dark"
// or "light" class on <html> rather than to anything of ours, and several of
// its own components — the navbar among them — key their styling off that
// class rather than off the --kx-* properties. The site's kx-theme picker has
// to drive that class too, or picking a light palette leaves Hextra's own
// chrome dark. Computed here rather than hardcoded as "only 'light' is light"
// in the JS that reads it, so a future light palette doesn't have to be found
// and special-cased by hand in two separate scripts.
func renderData() (string, error) {
	type swatch struct {
		Name       string `json:"name"`
		Accent     string `json:"accent"`
		Background string `json:"background"`
		Border     string `json:"border"`
		Mode       string `json:"mode"`
	}
	swatches := make([]swatch, 0, len(names()))
	for _, name := range names() {
		styles, err := theme.WebStyles(name)
		if err != nil {
			return "", err
		}
		mode, err := backgroundMode(styles[theme.Background])
		if err != nil {
			return "", fmt.Errorf("%s: background %q: %w", name, styles[theme.Background], err)
		}
		swatches = append(swatches, swatch{
			Name:       name,
			Accent:     styles[theme.Accent],
			Background: styles[theme.Background],
			Border:     styles[theme.Border],
			Mode:       mode,
		})
	}
	encoded, err := json.MarshalIndent(swatches, "", "  ")
	if err != nil {
		return "", err
	}
	return string(encoded) + "\n", nil
}

// backgroundMode classifies a background as "light" or "dark" by HSL
// lightness, reusing the same conversion block already computes for Hextra's
// primary-color ramp. 60% is a wide margin either side of every registered
// background — the lightest dark-mode background sits under 20%, the one
// light-mode background at 100% — so it is not a threshold that needs
// retuning as palettes are added.
func backgroundMode(hex string) (string, error) {
	_, _, lightness, err := toHSL(hex)
	if err != nil {
		return "", err
	}
	if lightness >= 60 {
		return "light", nil
	}
	return "dark", nil
}

// Names returns the palettes the site offers, in registry order.
func names() []string {
	var kept []string
	for _, name := range theme.Names() {
		if !skipped[name] {
			kept = append(kept, name)
		}
	}
	return kept
}

func render() (string, error) {
	var out strings.Builder
	out.WriteString("/* Generated by tools/gen-site-theme from internal/theme. Do not edit.\n" +
		" *\n" +
		" * Every palette kx renders in the terminal, as CSS. Two things read these:\n" +
		" * the kx-* properties style the page's own components, and the three\n" +
		" * primary-* properties are Hextra's, which derives its whole color ramp\n" +
		" * from them — so choosing a kx palette recolors the theme's chrome too.\n" +
		" */\n")

	// Hextra puts .dark on <html> for its own toggle. An explicit pick sets
	// data-kx-theme, which is written last so it wins over both defaults.
	light, err := block(defaultLight)
	if err != nil {
		return "", err
	}
	out.WriteString("\n:root {\n" + light + "}\n")

	dark, err := block(defaultDark)
	if err != nil {
		return "", err
	}
	out.WriteString("\n.dark {\n" + dark + "}\n")

	for _, name := range names() {
		declarations, err := block(name)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&out, "\n[data-kx-theme=%q] {\n%s}\n", name, declarations)
	}

	// The terminal sample is captured once per palette (see
	// tools/gen-site-terminal), and only the active one is shown. Emitted here
	// because this is where the palette list already lives: a rule pair
	// written by hand would be the thing that goes missing when a palette is
	// added.
	out.WriteString("\n/* Show only the media matching the active palette: the terminal captures\n" +
		"   (tools/gen-site-terminal) and the report screenshots\n" +
		"   (demo/shoot-reports.py). */\n")
	for _, attribute := range []string{"data-kx-terminal", "data-kx-shot"} {
		fmt.Fprintf(&out, "[%s] { display: none; }\n", attribute)
		fmt.Fprintf(&out, "[%s=%q] { display: block; }\n", attribute, defaultDark)
		for _, name := range names() {
			if name == defaultDark {
				continue
			}
			fmt.Fprintf(&out,
				"[data-kx-theme=%q] [%s=%q] { display: none; }\n"+
					"[data-kx-theme=%q] [%s=%q] { display: block; }\n",
				name, attribute, defaultDark, name, attribute, name)
		}
	}

	// The picker needs the list, and duplicating it in a template is how it
	// would come to disagree with the registry.
	fmt.Fprintf(&out, "\n/* Palettes: %s */\n", strings.Join(names(), ", "))
	return out.String(), nil
}

// block renders one palette's declarations.
func block(name string) (string, error) {
	styles, err := theme.WebStyles(name)
	if err != nil {
		return "", err
	}

	var out strings.Builder
	keys := make([]string, 0, len(styles))
	for key := range styles {
		keys = append(keys, key)
	}
	// Sorted so the file is byte-stable; Go map iteration is randomised and
	// the hook compares the rendered output against what is on disk.
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(&out, "  --kx-%s: %s;\n", strings.ReplaceAll(key, ".", "-"), styles[key])
	}

	// Hextra builds --color-primary-50 through -900 from these three, so the
	// accent has to reach it as HSL components rather than as a hex color.
	hue, saturation, lightness, err := toHSL(styles[theme.Accent])
	if err != nil {
		return "", fmt.Errorf("%s: accent %q: %w", name, styles[theme.Accent], err)
	}
	fmt.Fprintf(&out, "  --primary-hue: %sdeg;\n", trim(hue))
	fmt.Fprintf(&out, "  --primary-saturation: %s%%;\n", trim(saturation))
	fmt.Fprintf(&out, "  --primary-lightness: %s%%;\n", trim(lightness))
	return out.String(), nil
}

// trim formats a component without trailing zeros, so the output reads like
// something a person wrote.
func trim(value float64) string {
	return strconv.FormatFloat(math.Round(value*10)/10, 'f', -1, 64)
}

// toHSL converts #rrggbb to hue in degrees and saturation and lightness in
// percent. WebStyles guarantees the hex form, and a test over every registered
// palette guards it, so anything else here is a bug rather than user input.
func toHSL(hex string) (hue, saturation, lightness float64, err error) {
	value := strings.TrimPrefix(hex, "#")
	if len(value) != 6 {
		return 0, 0, 0, fmt.Errorf("want #rrggbb")
	}
	parsed, parseErr := strconv.ParseUint(value, 16, 32)
	if parseErr != nil {
		return 0, 0, 0, parseErr
	}
	red := float64((parsed>>16)&0xff) / 255
	green := float64((parsed>>8)&0xff) / 255
	blue := float64(parsed&0xff) / 255

	high := math.Max(red, math.Max(green, blue))
	low := math.Min(red, math.Min(green, blue))
	lightness = (high + low) / 2

	if high == low {
		// Achromatic: hue is undefined and any value renders the same grey.
		return 0, 0, lightness * 100, nil
	}

	span := high - low
	saturation = span / (1 - math.Abs(2*lightness-1))
	switch high {
	case red:
		hue = math.Mod((green-blue)/span, 6)
	case green:
		hue = (blue-red)/span + 2
	default:
		hue = (red-green)/span + 4
	}
	hue *= 60
	if hue < 0 {
		hue += 360
	}
	return hue, saturation * 100, lightness * 100, nil
}
